dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}
  from_key2: ${PRIVATE_KEY2}

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.3

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.3'